"""Add uploaded_subtitle_filename to Video model

Revision ID: 2717b4474e46
Revises: 
Create Date: 2025-03-27 11:42:21.735858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2717b4474e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_subtitle_filename', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('uploaded_subtitle_filename')

    # ### end Alembic commands ###
